import Head from "next/head";

import { ApolloClient, InMemoryCache, gql } from "@apollo/client";
import Header from "../src/components/Header";
import Footer from "../src/components/Footer";
import Layout from "../src/components/Layout";
import Content from "../src/components/Content";
import Bookshelf from "../src/components/Bookshelf";
import Hero from "../src/components/Hero";
import Quotation from "../src/components/Quotation";

import useMediaQuery from "../src/hooks/useMediaQuery";

export default function Home({ books }) {
  const isMobile = useMediaQuery(768);

  return (
    <>
      <Head>
        {/* generate from cms */}

        <title>Bright Ideas</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Header />

        <Content>
          {isMobile ? (
            <Hero
              image={`/images/heroImageWithText.png`}
              width={1024}
              height={600}
            />
          ) : (
            <Hero
              image={`/images/heroImageWithTextCropped.png`}
              width={1024}
              height={400}
            />
          )}
          {/* TODO: replace div with vertical spacing component */}
          <div style={{ margin: isMobile ? "1rem 0" : "2rem 0" }}>
            <Quotation>
              "Little books of inspirational verse {isMobile && <br />}
              and prose"
              <br />
              by P J Perkins
            </Quotation>
          </div>
          <Bookshelf books={books} link="[slug]" />
          <div style={{ margin: "2rem 0" }}>
            <Quotation
              cite="/bright-ideas-in-action/the-value-of-a-moment"
              source="The Value of a Moment"
              author="P J Perkins"
            >
              <p>
                "Sharing an idea that helps another,
                {isMobile && <br />} Is the best moment <br />
                You can ever have - It is a moment of love."
              </p>
            </Quotation>
          </div>
        </Content>
        <Footer />
      </Layout>
    </>
  );
}

export async function getStaticProps() {
  const client = new ApolloClient({
    uri: "https://larkin-cms.herokuapp.com/graphql",
    cache: new InMemoryCache(),
  });

  const { data } = await client.query({
    query: gql`
      query getBooks {
        books {
          id
          title
          slug
          poems {
            id
            title
            slug
          }
        }
      }
    `,
  });

  return {
    props: {
      books: data.books,
    },
  };
}
